# Generated by Django 4.2.1 on 2023-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
