# Generated by Django 4.2.1 on 2023-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(default='none', max_length=100)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('feed', models.TextField(null=True)),
            ],
        ),
    ]
