# Generated by Django 4.2.1 on 2023-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='room_video/%Y/%m/%d'),
        ),
    ]
