# Generated by Django 4.2.1 on 2023-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comment_blog_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking',
            field=models.FileField(default=1, upload_to='booking/'),
            preserve_default=False,
        ),
    ]
