# Generated by Django 4.2.1 on 2023-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booking',
            field=models.URLField(),
        ),
    ]
