# Generated by Django 4.2.1 on 2023-08-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_room_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='video',
        ),
    ]
